// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Simple.Treavor.Infrastructure.Data;

#nullable disable

namespace Simple.Treavor.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230325075124_SEED-CONTRY-HOTEL")]
    partial class SEEDCONTRYHOTEL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Simple.Treavor.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pakistan",
                            ShortName = "PK"
                        },
                        new
                        {
                            Id = 2,
                            Name = "India",
                            ShortName = "IND"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United State America",
                            ShortName = "USA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Europe",
                            ShortName = "ER"
                        });
                });

            modelBuilder.Entity("Simple.Treavor.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Karachi",
                            CountryId = 1,
                            Name = "Shinwari",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Islamabad",
                            CountryId = 1,
                            Name = "Aflaton",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Karachi",
                            CountryId = 1,
                            Name = "Mumbai",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Karachi",
                            CountryId = 3,
                            Name = "Bisbine",
                            Rating = 2.5
                        },
                        new
                        {
                            Id = 5,
                            Address = "Aurgentinia",
                            CountryId = 3,
                            Name = "Pasta",
                            Rating = 2.5
                        });
                });

            modelBuilder.Entity("Simple.Treavor.Data.Hotel", b =>
                {
                    b.HasOne("Simple.Treavor.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
